### ISSUE TITLE
--jmespath and --format options are not working

### ISSUE THREAD

**Issue by cladmi** [iot-lab/ssh-cli-tools#35]
`iotlab-ssh --help` shows `--jmespath` and `--format ` options like the cli-tools but it does not actually take them into account.

### Actual output

```
iotlab-ssh --jmespath='keys(values(@)[0])' --fmt='int'  reset-m3 --list lyon,a8,1
{
    "reset-m3": {
        "0": [
            "node-a8-1.lyon.iot-lab.info"
        ]
    }
}
```

### Expected output

```
iotlab-ssh --jmespath='keys(values(@)[0])' --fmt='int'  reset-m3 --list lyon,a8,1
0
```

For reference, on iotlab-node:

```
iotlab-node --jmespath='keys(@)[0]' --fmt='int' --list euratech,wsn430,2 --reset
0
```

### Related issues

I want to use it for a wrapped RIOT support and would help for checking return value:

https://github.com/RIOT-OS/RIOT/pull/9011#issuecomment-385057836

**Comment by aabadie** [comment]
@cladmi, see #36

**Comment by aabadie** [comment]
#36 is merged so I close this one.

**Comment by aabadie** [comment]
@cladmi, I published a [new release](https://pypi.org/project/iotlabsshcli) on Pypi that contains the fix. It's also deployed on the IoT-LAB frontends.

**Comment by cladmi** [comment]
Thank you.

**Comment by cladmi** [comment]
It is currently not deployed in lyon.iot-lab.info:

```
harter@lyon:~$ iotlab-ssh --version
0.2.0
```

**Comment by aabadie** [comment]
> It is currently not deployed in lyon.iot-lab.info

it's updated:
```
abadie@lyon:~$ iotlab-ssh --version
0.2.2
```

**Comment by aabadie** [comment]
> It is currently not deployed in lyon.iot-lab.info

it's updated:
```
abadie@lyon:~$ iotlab-ssh --version
0.2.3
```

**Comment by cladmi** [comment]
Thanks
