### ISSUE TITLE
Impossible to use iotlab-ssh on the frontend ?

### ISSUE THREAD

**Issue by rgrunbla** [iot-lab/ssh-cli-tools#46]
Hello.
The [doc](https://iot-lab.github.io/docs/tools/ssh-cli/) states that "*it’s not mandatory to install them on your computer as they are installed by default on all IoT-LAB SSH fronted servers*". At the same time, it seems executing iotlab-ssh on the frontend servers does not give the expected results:
```
grunblat@grenoble:~/A8$ iotlab-ssh --verbose run-cmd "uname -a" -l grenoble,a8,227
Proxy authentication failed. Exception from tunnel client: ('Authentication error while connecting to %s:%s - %s', 'grenoble.iot-lab.info', 22, AuthenticationError())
Failed to run on host None - ('Proxy authentication failed. Exception from tunnel client: %s', AuthenticationError('Authentication error while connecting to %s:%s - %s', 'grenoble.iot-lab.info', 22, AuthenticationError()))
{
    "run-cmd": {
        "1": [
            "node-a8-227.grenoble.iot-lab.info"
        ]
    }
}
grunblat@grenoble:~/A8$ ssh root@node-a8-227.grenoble.iot-lab.info "uname -a"
Linux node-a8-227 3.19.0-yocto-standard-iotlab #1 Fri Jun 15 09:42:36 EDT 2018 armv7l armv7l armv7l GNU/Linux
```

Is this a bug ?

Thanks,
Rémy

**Comment by fsaintma** [comment]
Hi @rgrunbla 
Have you done the requirements ? You must upload your auto-generated SSH public key on the frontend ($ cat ~/.ssh/id_rsa.pub) on the IoT-LAB webportal user profile.
Best regards.

**Comment by rgrunbla** [comment]
Since then I wiped my ~/.ssh directory multiple time to test some automation with the platform so, the answer might be "no". I'm executing some experiments right now so I'm closing this issue until I have the time to try again, i'll re-open if necessary. Thanks !

**Comment by rgrunbla** [comment]
I think I got it: I'm using an ed25519 ssh key, which I uploaded into the my ssh directory (and which is also located in the IoT-LAB webportal user profile). Is the location of the key (a RSA key) important ?
