### ISSUE TITLE
TypeError: run_command() got an unexpected keyword argument 'return_list'

### ISSUE THREAD

**Issue by danielrosendo** [iot-lab/ssh-cli-tools#51]
The **return_list** argument has been removed in pssh: https://github.com/ParallelSSH/parallel-ssh/commit/31303180fae324aff4aca98e441126fe0d58bec7#diff-a9fa5b1adda1202fd9a4755c006f96b238b46d8dfffcb57dccd2483426d23d7d
and since iotlabsshcli always install the latest version, it breaks (https://github.com/iot-lab/ssh-cli-tools/blob/master/setup.py#L60-L61)

```
res = iotlabsshcli.open_linux.wait_for_boot(
  File "/home/drosendo/git/venv/lib/python3.9/site-packages/iotlabsshcli/open_linux.py", line 100, in wait_for_boot
    return {"wait-for-boot": ssh.wait(max_wait)}
  File "/home/drosendo/git/venv/lib/python3.9/site-packages/iotlabsshcli/sshlib/open_linux_ssh.py", line 180, in wait
    result_cmd = self.run_command("uptime",
  File "/home/drosendo/git/venv/lib/python3.9/site-packages/iotlabsshcli/sshlib/open_linux_ssh.py", line 205, in run_command
    output = client.run_command(command, stop_on_errors=False,
TypeError: run_command() got an unexpected keyword argument 'return_list'
```

**Comment by fsaintma** [comment]
Hi @danielrosendo 

This is a mistake on my part :). parallel-ssh releases many versions with important changes. I will fix the version in setup.py to avoid the problem. Can you confirm me that the error is on the last version by installing it on your computer ? On the SSH frontend we have a version 2.5.3 which should work correctly. You can use this version and if you confirm me that it works I will use this last one and push a fix.
```
root@grenoble:~# pip freeze | grep ssh
iotlabsshcli==1.0.1
parallel-ssh==2.5.3
```
Then when I have time I'll look if there is any interest to update the version and study the parallel-ssh changelog :)
Bets regards.

**Comment by danielrosendo** [comment]
Hi @fsaintma 

It works for version `parallel-ssh==2.5.4` and fails if `>2.5.4`.

Thanks!

**Comment by fsaintma** [comment]
Fix by https://github.com/iot-lab/ssh-cli-tools/pull/52
