### ISSUE TITLE
psutil is frozen to 5.7.0

### ISSUE THREAD

**Issue by msimonin** [iot-lab/ssh-cli-tools#53]
Hi there,

Originally reported [here](https://framateam.org/enoslib/pl/8gs4ijpkcigopbgs6h5hktrgfe) by @Ezibenroc
As described in the dependencies, `psutil` is frozen to 5.7.0 but might be too old / buggy (see https://github.com/giampaolo/psutil/issues/1708)

Is there a reason to force this specific version ?

**Comment by fsaintma** [comment]
Hi @msimonin 
I have just removed the psutil version dependency in the setup.py. (tested with psutil 5.9.0 without problem). I thought I would wait for more changes before releasing a new package version.
Best regards.

**Comment by msimonin** [comment]
@fsaintma great, thanks !
